* COMMON SCRIPTS FOR LABELLING VARIABLES (la var command)la var state        "State name"
la var county       "County name"
la var fips_state   "State FIPS"
la var fips_county  "County FIPS"
la var year         "Year"

la var tax_amnt "Sales tax data: origin sales/collection amount records from local gov"
la var tax_unit "Sales tax data: unit/scale of the original records"
la var tax_rept "Sales tax data: report types"
la var tax_type "Sales tax data: collection types"
la var tax_ttpy "Sales tax data: reporting year type, calendar or fiscal year"
la var tax_rate "Sales tax data: applied rate in digital, -1 unavailable, -2 unapplicable"
la var tax_rtpy "Sales tax data: type of the applied rate"
la var tax_shar "Sales tax data: by-year share/distribution, i.e. c/sum(c)"
la var tax_lshr "Sales tax data: by-year log share/distribution, i.e. ln(c)/sum(ln(c))"
la var tax_stpy "Sales tax data: based on what the by-year share/distribution is computed"
